FROM ubuntu:22.04
RUN apt-get update && apt-get install -y \
    libboost-system1.74.0 \
    libboost-thread1.74.0 \
    libboost-regex1.74.0 \
    libboost-date-time1.74.0 \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*
# Copy binary and settings
COPY build/x86_64/instrument-data-link-x86_64 /usr/local/bin/datalink
COPY settings/data_link-settings.json /usr/local/bin/settings/data_link-settings.json

# Set working directory
WORKDIR /usr/local/bin

# Run datalink
ENTRYPOINT ["/usr/local/bin/datalink"]
